// Code generated by mockery v2.10.6. DO NOT EDIT.

package pubsubMock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Subscriber is an autogenerated mock type for the Subscriber type
type Subscriber struct {
	mock.Mock
}

// Subscriber provides a mock function with given fields: ctx, callback
func (_m *Subscriber) Subscriber(ctx context.Context, callback func(context.Context, interface{}) error) {
	_m.Called(ctx, callback)
}
